Oauth: Add balena api handshake
product-os/jellyfish pull request #2925
Opened 2019-12-18 13:51 UTC by karaxuna

Change-type: minor
Connects-to: #2724

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

2019-12-18 13:56 UTC, jviotti requested changes

2020-01-02 11:24 UTC, LucianBuzzo approved these changes
Looks good to me, the `whoami` abstraction is :ok_hand:

2020-01-06 13:12 UTC, jviotti requested changes
Just a small change requested, but we can hopefully merge today

2020-01-06 17:05 UTC, jviotti approved these changes

2020-01-07 08:34 UTC, merged