Run 1 replica of jellyfish-ui, instead of 3
product-os/jellyfish pull request #3006
Opened 2020-01-14 15:27 UTC by ffissore

Run 1 replica of jellyfish-ui, instead of 3. Jellyfish-ui is an nginx container serving static files, so running multiple replicas provides no advantage

Change-type: patch
Signed-off-by: Federico Fissore <federico@balena.io>

2020-01-14 15:47 UTC, jviotti approved these changes

2020-01-15 14:43 UTC, LucianBuzzo approved these changes

2020-01-17 00:25 UTC, joshbwlng approved these changes

2020-01-22 14:39 UTC, mikesimos requested changes
We need at least 2 replicas for high availability. Running 1 replica means running a risk of service disruption/downtime, every-time an underlying node fails, or on potential pod failure. We should close/not merge this PR.

2020-01-23 09:56 UTC, closed without merging