add mailgun integration
product-os/jellyfish pull request #3072
Opened 2020-02-05 07:06 UTC by ljewalsh

With sendEmail function so we can send emails to users

2020-02-06 01:02 UTC, grahammcculloch reviewed
Just some little initial comments!

2020-03-04 06:55 UTC, joshbwlng approved these changes

2020-03-04 07:03 UTC, ffissore approved these changes

2020-03-04 09:05 UTC, jviotti requested changes
The code in `lib/sync/integrations` is about syncing bi-directional data and the classes in there have a predefined interface that we are not respecting here (i.e. `.translate()` and `.mirror()`) which operates on cards.

Can we refactor the implementation so that:

- The `.sendEmail()` function becomes `.mirror()`, matching the arguments of the `.mirror()` methods in the other integrations
- We have a new `email` card type that represents an email being sent
- Make `.mirror()` operate on `email` cards. Basically it gets an `email` card as an argument and sends an e-mail in response to that card
- Add a mailgun mirror action like we do for other integrations
- Add a triggered action so that we call such function when we insert `email` cards into the system

?

2020-03-09 09:15 UTC, LucianBuzzo reviewed
The code looks good, but I think it needs to live in a different file location. This code doesn't "sync" anything. I think it might be sensible to put it under `lib/mail`. Also, is there any reason why we aren't using a pre-existing package? e.g. https://www.npmjs.com/package/mailgun-js

2020-03-10 06:59 UTC, LucianBuzzo approved these changes

2020-03-10 09:54 UTC, jviotti approved these changes

2020-03-11 01:08 UTC, merged