Implement file upload on thread creation
product-os/jellyfish pull request #3136
Opened 2020-02-19 12:16 UTC by karaxuna

Change-type: minor

***

**Currently supports only single file upload**

<img width="380" alt="Screenshot 2020-02-19 at 16 15 18" src="https://user-images.githubusercontent.com/2152815/74833520-0f19ad80-5333-11ea-8810-54397c9ba728.png">

<img width="376" alt="Screenshot 2020-02-29 at 01 48 52" src="https://user-images.githubusercontent.com/2152815/75590042-de094d80-5a95-11ea-931b-4c29516e3071.png">

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

2020-02-20 10:52 UTC, ffissore approved these changes

2020-02-26 14:30 UTC, LucianBuzzo approved these changes

2020-02-28 07:50 UTC, grahammcculloch requested changes
Just a couple tiny suggestions

2020-03-02 08:19 UTC, ffissore approved these changes

2020-03-02 08:32 UTC, grahammcculloch approved these changes

2020-03-02 09:17 UTC, merged