Add the `password-reset` default card.
product-os/jellyfish pull request #3163
Opened 2020-02-26 02:30 UTC by jimsynz

Implements https://github.com/product-os/jellyfish/projects/10#card-33658506)

There appear to be no unit tests for any card loader code that I can see. If I'm missing something then please let me know and I'll happily add them.

2020-03-01 20:38 UTC, ljewalsh approved these changes

2020-03-02 00:58 UTC, grahammcculloch requested changes
Couple small suggestions

2020-03-09 01:46 UTC, ljewalsh approved these changes

2020-03-09 03:24 UTC, grahammcculloch approved these changes

2020-03-09 03:28 UTC, merged