front: Don't consider private inboxes
product-os/jellyfish pull request #3175
Opened 2020-02-26 18:58 UTC by jviotti

If a conversation starts on a private personal inbox and is then moved
to i.e. support, then the conversation will belong to both inboxes at
the same time.

When looking what inbox a thread belongs to, we shouldn't take into
account private ones, as we don't know what to do with them.

Change-type: patch

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

2020-02-27 20:10 UTC, ljewalsh requested changes
Looks good to me. I wonder if we can put this in a named variable to make it clear what it's doing for future devs.

Also, should we have a test for this?

2020-02-28 07:34 UTC, LucianBuzzo approved these changes

2020-02-28 08:26 UTC, ffissore requested changes
Do we have a test for this case already? If not, can we add one?

2020-03-03 14:38 UTC, ffissore approved these changes

2020-03-03 15:27 UTC, merged