balena-api: Check that geoip result is defined
product-os/jellyfish pull request #3187
Opened 2020-02-27 20:11 UTC by jviotti

This can be the case if the ip doesn't resolve to any valid location.

Change-type: patch
Fixes: https://sentry.io/share/issue/266bb268586a40e092c37777872ddca5/

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

2020-02-28 00:58 UTC, grahammcculloch approved these changes

2020-02-28 04:17 UTC, joshbwlng approved these changes

2020-02-28 08:22 UTC, ffissore requested changes
Do we have a test for this case already? If not, can we add it?

2020-03-04 07:29 UTC, ffissore approved these changes

2020-03-04 22:32 UTC, merged