balena-api: Retry .whoami() handler on 429
product-os/jellyfish pull request #3188
Opened 2020-02-27 20:14 UTC by jviotti

Change-type: patch
Fixes: https://sentry.io/share/issue/ffceb80789074ce3bce0b7f7f50d952f/

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

2020-02-28 01:02 UTC, grahammcculloch approved these changes

2020-02-28 04:18 UTC, joshbwlng approved these changes

2020-02-28 08:38 UTC, ffissore requested changes
Do we have a test for this case already? If not, can we add one?

2020-03-04 07:28 UTC, ffissore approved these changes

2020-03-04 20:49 UTC, merged