github: Fallback for issue mirror URL
product-os/jellyfish pull request #3189
Opened 2020-02-27 20:22 UTC by jviotti

Change-type: patch
Fixes: https://sentry.io/share/issue/b79ad9abb1c74de5b3d8de815ed07e3a/

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

2020-02-28 01:06 UTC, grahammcculloch reviewed
Just one question for you...

2020-02-28 08:41 UTC, ffissore requested changes
Do we have a test for this case already? If not, can we add one? (sorry for repeating this ad nauseam, it must be the friday mood)

2020-03-04 00:37 UTC, grahammcculloch approved these changes

2020-03-04 07:27 UTC, ffissore approved these changes

2020-03-04 20:13 UTC, merged