Verify parameters on POST signup
product-os/jellyfish pull request #3232
Opened 2020-03-04 07:05 UTC by joshbwlng

Change-type: patch
Signed-off-by: Josh Bowling <josh@balena.io>

***

ref: https://github.com/product-os/jellyfish/issues/3159

Add some simple string checks on `POST /api/v2/signup` request parameters.

2020-03-04 07:49 UTC, ffissore requested changes
Can we add a test case for this check? Or do we already have one?

2020-03-09 01:39 UTC, grahammcculloch approved these changes
LGTM - great work @ffissore for requesting a test and @joshbwlng for writing some lovely simple tests!

2020-03-09 08:15 UTC, ffissore requested changes

2020-03-09 08:20 UTC, ffissore approved these changes

2020-03-09 08:39 UTC, merged