ui-components: new re-usable LinksProvider component
product-os/jellyfish pull request #3431
Opened 2020-03-29 08:44 UTC by grahammcculloch

Can be used with matching withLinks and withLink higher order components, or useLink and useLinks hooks.

Change-type: minor
Signed-off-by: Graham McCulloch <graham@balena.io>

***

In some situations (e.g. dealing with card ownership and the guided handover flow) we need to maintain a cache of linked cards that can be accessed and updated by different child components within a certain context. This is where the generic `LinksProvider` component and its associated HOCs and hooks come in.

Example usage:

```javascript
const SomeComponent = ({ card }) => {
  const { cardOwner, updateCardOwner } = useLink('is owned by', 'cardOwner', card.id)
  return <div>...</div>
}
```

```javascript
<LinksProvider sdk={sdk} cards={[ card ]} link="is owned by">
  ...
  <SomeComponent card={card} />
</LinkProvider>
```

2020-03-29 11:25 UTC, karaxuna requested changes
Additional question: why can't we store links inside redux store?

2020-03-30 00:26 UTC, ljewalsh requested changes

2020-03-30 02:43 UTC, ljewalsh approved these changes

2020-03-30 11:45 UTC, karaxuna approved these changes

2020-03-31 00:45 UTC, merged