Update Katapult deploy script
product-os/jellyfish pull request #3585
Opened 2020-04-25 00:19 UTC by ab77

Change-type: minor
Signed-off-by: ab77 <anton@balena.io>

2020-04-25 00:39 UTC, petrosagg requested changes

2020-04-25 18:38 UTC, petrosagg approved these changes

2020-04-26 04:24 UTC, joshbwlng approved these changes

2020-04-26 05:06 UTC, joshbwlng requested changes
Should this change really be considered a `Change-type: minor` and not `patch`?

2020-04-27 00:10 UTC, joshbwlng approved these changes

2020-04-27 00:49 UTC, merged