Add a reworked `jsonschema2sql` under a feature gate
product-os/jellyfish pull request #3613
Opened 2020-04-28 19:10 UTC by Ereski

This rework is necessary to support further improvements, some of which are already incorporated in this commit such as:

- A new query structure for linked cards relying on plain joins instead of subqueries. Benchmarks show that this new structure is consistently faster than the old query structure even on difficult edge cases;
- Better error checking instead of silently ignoring wrong schemas;
- Correct query generation for some nested keywords (i.e. nested `required` that is currently ignored);
- Other minor improvements and handling of rare corner cases.

This PR also prunes:

- The experimental alternative query generator that supports `$$links` within `$$links`. This code path is unused in production and conflicts with this rewrite. If needed, this feature can be reintroduced in the future;
- Support for setting `null` as the schema for a linked cards, signifying that the link must not exist. This functionality is not currently used and would be obsoleted anyway when support for nested links lands;
- Support for the following keywords (may be readded later):
  - `default`
  - `patternProperties`
  - `propertyNames`
  - `formatMaximum`
  - `formatMinimum`

Change-type: minor
Signed-off-by: Carol Schulze <carol@balena.io>

2020-04-29 05:36 UTC, ljewalsh submitted a review, later dismissed
Hey @Ereski! I dived into this for a while but got distracted trying to setup a debugger on vim so I could play around with it easier. Here are just a couple of comments. I'd like to have had more for you but it will have to wait for tomorrow

2020-04-29 10:01 UTC, LucianBuzzo requested changes
Out of curiosity, does the suffix `Visitor` have a special meaning outside of this work?

2020-05-04 18:58 UTC, petrosagg approved these changes

2020-05-05 12:57 UTC, LucianBuzzo approved these changes

2020-05-05 22:09 UTC, merged