backend: Add initial full text search support
product-os/jellyfish pull request #3616
Opened 2020-04-29 09:50 UTC by joshbwlng

Change-type: patch
Signed-off-by: Josh Bowling <josh@balena.io>

***

This PR:
- builds `tsvector` partial indexes on init for each card field that has `fullTextSearch: true`
  - Indexes for `text[]` columns are created using a new custom function `immutable_array_to_string()` in order to achieve the same `tsvector` results
  - Indexes for values that exist under `data` are created using `jsonb_to_tsvector()`
  - Indexes for `text` columns are created using `to_tsvector()`
- adds `fullTextSearch` keyword handlers to the `jsonschema2sql` compiler
- adds full text search functionality, initially for these cards:
  - `support-thread`
    - `name`, `tags`, `data.category`, `data.tags`, `data.environment`, `data.description`, `data.inbox`, `data.statusDescription`
  - `sales-thread`
    - `name`, `tags`, `data.tags`, `data.inbox`, `data.statusDescription`, `data.status`
  - `thread`
    - `data.tags`, `data.description`
  - `message`
    - `data.timestamp`, `data.payload.file.name`, `data.payload.message`
  - `whisper`
    - `data.timestamp`, `data.payload.file.name`, `data.payload.message`

***

Full-text search using `tsvector`s will allow to perform searches more efficiently by reducing terms to their stems (e.g. `cats` => `cat`) and removing "noise" that will not help in search (e.g. a, and, the).

Here are a couple examples of what some text looks like after being transformed into `tsvector`s using [`to_tsvector`](https://www.postgresql.org/docs/9.1/textsearch-controls.html):
```
# SELECT to_tsvector('english', 'cats and dogs');
   to_tsvector
-----------------
 'cat':1 'dog':3

# SELECT to_tsvector('english', 'Add full-text search support for strings nested inside of complex structures');
                                                       to_tsvector
--------------------------------------------------------------------------------------------------------------------------
 'add':1 'complex':12 'full':3 'full-text':2 'insid':10 'nest':9 'search':5 'string':8 'structur':13 'support':6 'text':4
```

These `tsvector`s are stored in partial indexes, one index per field per card type. For example, a partial index for the `data.payload.message` field on the `message` card will be created as `message__data_payload_message__search_idx`.

Search queries are prepared to be ran against these indexes using [`plainto_tsquery`](https://www.postgresql.org/docs/9.1/textsearch-controls.html): 
```
SELECT slug FROM cards WHERE to_tsvector('english', cards.data#>'{description}') @@ plainto_tsquery('english', 'job explore') AND type='support-thread@1.0.0';
```

***

Things to be done in subsequent PRs:
- Add full-text search support for strings nested inside of complex structures (object->array->object->string) such as `data.payload.attachments.name` in `message` cards

Closes https://github.com/product-os/jellyfish/issues/386

2020-05-07 02:00 UTC, grahammcculloch reviewed
A few more questions for you Josh :-)

Also - have you tried a test that does a single full text search on message _and_ whisper cards? Does it work?

**Reply from Josh:** Don't have that test written up at the moment, but will look at adding one. I'm not modifying any core SQL generation logic so it should work like current `regexp` searches do, but I'll double-check.

2020-05-25 12:49 UTC, Ereski requested changes
A lot of comments, mostly related to handling of types.

2020-05-27 07:31 UTC, Ereski submitted a review, later dismissed

2020-05-28 11:32 UTC, Ereski approved these changes

2020-05-28 12:24 UTC, merged