Update CardField to display arrays and objects as a HTML list
product-os/jellyfish pull request #3827
Opened 2020-05-20 05:12 UTC by ljewalsh

At the moment, when we display the fields on a card, arrays come out looking a little janky with the index of each value as the title:
<img width="443" alt="Screen Shot 2020-05-20 at 5 10 26 PM" src="https://user-images.githubusercontent.com/6325359/82407265-d8cc0580-9abc-11ea-9499-78ebbcfa6cdf.png">

This PR updates the CardField component so that we display both objects an arrays as a `<ul>` HTML tag. Each item in the list or key/value in the object are displayed as a`<li>` within the `<ul>`:
<img width="731" alt="Screen Shot 2020-05-26 at 11 52 44 AM" src="https://user-images.githubusercontent.com/6325359/82848403-6c7f5500-9f47-11ea-907d-7927283840be.png">

Key/values are displayed as <li>key: value</li>
<img width="441" alt="Screen Shot 2020-05-26 at 11 55 58 AM" src="https://user-images.githubusercontent.com/6325359/82848510-def03500-9f47-11ea-9a15-8a81bc62f6bd.png">

Also adds some basic enzyme tests

2020-05-20 05:58 UTC, grahammcculloch requested changes
I like the new tests - this will be useful as we extend the `CardField` functionality in the future!

Just one suggested change to account for arrays of items that aren't strings.

2020-05-20 10:42 UTC, karaxuna requested changes

2020-05-21 08:41 UTC, LucianBuzzo requested changes

2020-05-25 01:53 UTC, grahammcculloch approved these changes
Approved - on the understanding that we're going to revisit this component soon to handle different field types (e.g. arrays of objects) in a more comprehensive, testable way.

2020-05-26 03:53 UTC, closed without merging