Add Google Meet integration
product-os/jellyfish pull request #3836
Opened 2020-05-21 07:15 UTC by grahammcculloch

The standard card actions component now includes a video link that will open a Google Meet specific for that card in a new tab/window. If no link exists, one will be created, saved to the card's data and then the link opened.

Change-type: minor
Signed-off-by: Graham McCulloch <graham@balena.io>

***
Before this PR was merged, we deployed the appropriate secret to the k8s cluster that will populate the following environment variable:

`INTEGRATION_GOOGLE_MEET_CREDENTIALS`

The value of this environment variable is the stringified JSON value of the Google Meet JWT credentials. For example:

```sh
export INTEGRATION_GOOGLE_MEET_CREDENTIALS="{\"type\":\"service_account\",\"project_id\":...
```

For reference, the relevant JSON can be found in the 'notes' section of the `Google Meet JWT` **passpack** item. 

***

Closes #3802 

![image](https://user-images.githubusercontent.com/2925657/82532942-84805e80-9b6c-11ea-98e1-6fbbd4789b06.png)

Summary of behaviour:
* Initially, a card has no `data.conferenceUrl` value set. A `VideoLink` is displayed in a lighter tone with the tooltip `Request a Google Meet for this <card-type>`. 
* When clicked, the link will display a spinning cog and the tooltip `Requesting a Google Meet for this <card-type>`.
* Clicking on the link will initiate a `action-google-meet` action.  This will use the Google API to: 
  1. create a calendar event
  1. extract the Google Meet URL from the created event data
  1. delete the event
  1. patch the `data.conferenceUrl` field in the card with the new Google Meet URL
  1. return the Google Meet URL to the client
* When the URL is returned from the server, the front-end opens it in a new tab/window
* Subsequent clicks on the `VideoLink` component will just directly open the Google Meet URL in a new tab/window with no interaction with the server.

2020-05-22 07:33 UTC, LucianBuzzo submitted a review, later dismissed

2020-05-22 09:37 UTC, cmfcruz submitted a review, later dismissed
LGTM

2020-05-25 01:10 UTC, joshbwlng requested changes

2020-05-25 01:37 UTC, joshbwlng approved these changes

2020-05-25 01:58 UTC, merged