Add summary event card
product-os/jellyfish pull request #3951
Opened 2020-06-01 15:39 UTC by karaxuna

Change-type: minor
Connects-to: #3907, #3908

***

**NOTE!** Marking summaries as read does not work. Depends on: https://github.com/product-os/jellyfish-client-sdk/pull/19

2020-06-02 00:19 UTC, grahammcculloch approved these changes

2020-06-02 05:33 UTC, ljewalsh requested changes
We talked about the summary workflow at an architecture call a few weeks ago and one thing that was brought up was that it might be better to store the summary as a separate card so that it can become part of the event flow of a thread, rather than storing it on the thread itself. This seems to better represent the way we are thinking about card updates as a series of events in the Jellyfish system

2020-06-12 13:04 UTC, LucianBuzzo requested changes

2020-07-14 11:23 UTC, LucianBuzzo approved these changes

2020-07-15 07:40 UTC, ljewalsh approved these changes

2020-07-16 14:07 UTC, merged