Update getUser trigger to find users by first and last name of a user as well as slug
product-os/jellyfish pull request #3972
Opened 2020-06-03 01:11 UTC by ljewalsh

At the moment when you type @ in a jellyfish thread, it triggers a search to find existing users by slug. This PR updates the trigger so that we also search for users by their name (first or last) if present.

I have also updated the component the trigger renders so that the full name of the user appears alongside the tag when a name is present.

https://www.loom.com/share/1e18468e1cfe4b128d89748d9df58e98

**NOTE:** A bunch of refactoring has been done in this PR to remove duplicate code and make the triggers simpler for testing. I have kept this as a separate commit so that it's easy to track the differences

2020-06-04 07:59 UTC, grahammcculloch requested changes
Sorry @ljewalsh I spotted one more small thing to fix up on the query. 

Apart from that its good to go!

2020-06-05 01:34 UTC, grahammcculloch requested changes

2020-06-09 00:20 UTC, grahammcculloch requested changes

2020-06-12 13:20 UTC, LucianBuzzo approved these changes

2020-06-14 22:10 UTC, ghost approved these changes

2020-06-15 01:41 UTC, grahammcculloch approved these changes

2020-06-15 05:03 UTC, merged