MessageInput: Allow pasting files
product-os/jellyfish pull request #4036
Opened 2020-06-09 13:08 UTC by karaxuna

Change-type: minor

***

**Please remember to write tests for your changes**. We aim to automatically
deploy `master` to production, and we can't safely do this without a solid
test suite!

2020-06-09 13:12 UTC, StefKors requested changes
Could you add a unit test for this?

2020-06-10 01:40 UTC, grahammcculloch reviewed
I like how simple this change is! 

However, I did test this out locally and I'm a bit worried about the behaviour. It's super easy to accidentally upload an image from the clipboard (e.g. when you thought you had some text in the clipboard but it's actually an image, or you just accidentally hit `Ctrl+V`). And once it's uploaded, there's (currently) no way to delete that message (via the UI). I would much rather see a solution that uploads an image and creates a markdown image reference to it in the message body - just like GitHub does. I guess that is more tricky in terms of authentication when fetching the uploaded image. 

But maybe this is an acceptable intermediate solution?

2020-06-10 09:24 UTC, grahammcculloch approved these changes

2020-06-10 12:40 UTC, StefKors approved these changes

2020-06-10 12:47 UTC, merged