Fixup flaky e2e tests
product-os/jellyfish pull request #4242
Opened 2020-06-25 07:00 UTC by grahammcculloch

**test: improve home channel navigation logic**
Use a helper method to ensure that expandable menu items are only clicked on if they are not expanded.

Change-type: patch
Signed-off-by: Graham McCulloch <graham@balena.io>

---
**test: Ensure toast notification is dismissed as part of test step**
This mitigates the situation where the notification blocks the item we are trying to click on next.

Change-type: patch
Signed-off-by: Graham McCulloch <graham@balena.io>

---
**test: only click Link Modal submit button once enabled**
Avoid the situation where we click on the Submit button before it is enabled.

Change-type: patch
Signed-off-by: Graham McCulloch <graham@balena.io>

---
**test: Fix flaky LinkModal test code**
Click on the Select option rather than clicking 'Enter' to select the Select option.

Change-type: patch
Signed-off-by: Graham McCulloch <graham@balena.io>

---

A small combination of improvements to tighten up flaky e2e UI tests.

Relates to #3341

2020-06-25 09:15 UTC, joshbwlng approved these changes

2020-06-25 09:30 UTC, joshbwlng requested changes
Requesting changes per the above timeout found in balenaCI

2020-06-30 02:05 UTC, ljewalsh approved these changes

2020-06-30 02:05 UTC, joshbwlng approved these changes

2020-06-30 02:52 UTC, merged